// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sdmxdl/format/protobuf/source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sdmxdl.Format.Protobuf.Web {

  /// <summary>Holder for reflection information generated from sdmxdl/format/protobuf/source.proto</summary>
  public static partial class SourceReflection {

    #region Descriptor
    /// <summary>File descriptor for sdmxdl/format/protobuf/source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzZG14ZGwvZm9ybWF0L3Byb3RvYnVmL3NvdXJjZS5wcm90bxIac2RteGRs",
            "LmZvcm1hdC5wcm90b2J1Zi53ZWIi2QMKDVNkbXhXZWJTb3VyY2USCgoCaWQY",
            "ASABKAkSQwoFbmFtZXMYAiADKAsyNC5zZG14ZGwuZm9ybWF0LnByb3RvYnVm",
            "LndlYi5TZG14V2ViU291cmNlLk5hbWVzRW50cnkSDgoGZHJpdmVyGAMgASgJ",
            "EhQKB2RpYWxlY3QYBCABKAlIAIgBARIQCghlbmRwb2ludBgFIAEoCRJNCgpw",
            "cm9wZXJ0aWVzGAYgAygLMjkuc2RteGRsLmZvcm1hdC5wcm90b2J1Zi53ZWIu",
            "U2RteFdlYlNvdXJjZS5Qcm9wZXJ0aWVzRW50cnkSDwoHYWxpYXNlcxgHIAMo",
            "CRIUCgd3ZWJzaXRlGAggASgJSAGIAQESFAoHbW9uaXRvchgJIAEoCUgCiAEB",
            "EhsKDm1vbml0b3JXZWJzaXRlGAogASgJSAOIAQEaLAoKTmFtZXNFbnRyeRIL",
            "CgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGjEKD1Byb3BlcnRpZXNF",
            "bnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQgoKCF9kaWFs",
            "ZWN0QgoKCF93ZWJzaXRlQgoKCF9tb25pdG9yQhEKD19tb25pdG9yV2Vic2l0",
            "ZUICUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource), global::Sdmxdl.Format.Protobuf.Web.SdmxWebSource.Parser, new[]{ "Id", "Names", "Driver", "Dialect", "Endpoint", "Properties", "Aliases", "Website", "Monitor", "MonitorWebsite" }, new[]{ "Dialect", "Website", "Monitor", "MonitorWebsite" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SdmxWebSource : pb::IMessage<SdmxWebSource>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SdmxWebSource> _parser = new pb::MessageParser<SdmxWebSource>(() => new SdmxWebSource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SdmxWebSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sdmxdl.Format.Protobuf.Web.SourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource(SdmxWebSource other) : this() {
      id_ = other.id_;
      names_ = other.names_.Clone();
      driver_ = other.driver_;
      dialect_ = other.dialect_;
      endpoint_ = other.endpoint_;
      properties_ = other.properties_.Clone();
      aliases_ = other.aliases_.Clone();
      website_ = other.website_;
      monitor_ = other.monitor_;
      monitorWebsite_ = other.monitorWebsite_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SdmxWebSource Clone() {
      return new SdmxWebSource(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "names" field.</summary>
    public const int NamesFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_names_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<string, string> names_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Names {
      get { return names_; }
    }

    /// <summary>Field number for the "driver" field.</summary>
    public const int DriverFieldNumber = 3;
    private string driver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Driver {
      get { return driver_; }
      set {
        driver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dialect" field.</summary>
    public const int DialectFieldNumber = 4;
    private string dialect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Dialect {
      get { return dialect_ ?? ""; }
      set {
        dialect_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "dialect" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDialect {
      get { return dialect_ != null; }
    }
    /// <summary>Clears the value of the "dialect" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDialect() {
      dialect_ = null;
    }

    /// <summary>Field number for the "endpoint" field.</summary>
    public const int EndpointFieldNumber = 5;
    private string endpoint_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Endpoint {
      get { return endpoint_; }
      set {
        endpoint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "properties" field.</summary>
    public const int PropertiesFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_properties_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> properties_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Properties {
      get { return properties_; }
    }

    /// <summary>Field number for the "aliases" field.</summary>
    public const int AliasesFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_aliases_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> aliases_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Aliases {
      get { return aliases_; }
    }

    /// <summary>Field number for the "website" field.</summary>
    public const int WebsiteFieldNumber = 8;
    private string website_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Website {
      get { return website_ ?? ""; }
      set {
        website_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "website" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWebsite {
      get { return website_ != null; }
    }
    /// <summary>Clears the value of the "website" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWebsite() {
      website_ = null;
    }

    /// <summary>Field number for the "monitor" field.</summary>
    public const int MonitorFieldNumber = 9;
    private string monitor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Monitor {
      get { return monitor_ ?? ""; }
      set {
        monitor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitor {
      get { return monitor_ != null; }
    }
    /// <summary>Clears the value of the "monitor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitor() {
      monitor_ = null;
    }

    /// <summary>Field number for the "monitorWebsite" field.</summary>
    public const int MonitorWebsiteFieldNumber = 10;
    private string monitorWebsite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MonitorWebsite {
      get { return monitorWebsite_ ?? ""; }
      set {
        monitorWebsite_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "monitorWebsite" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMonitorWebsite {
      get { return monitorWebsite_ != null; }
    }
    /// <summary>Clears the value of the "monitorWebsite" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMonitorWebsite() {
      monitorWebsite_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SdmxWebSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SdmxWebSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!Names.Equals(other.Names)) return false;
      if (Driver != other.Driver) return false;
      if (Dialect != other.Dialect) return false;
      if (Endpoint != other.Endpoint) return false;
      if (!Properties.Equals(other.Properties)) return false;
      if(!aliases_.Equals(other.aliases_)) return false;
      if (Website != other.Website) return false;
      if (Monitor != other.Monitor) return false;
      if (MonitorWebsite != other.MonitorWebsite) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= Names.GetHashCode();
      if (Driver.Length != 0) hash ^= Driver.GetHashCode();
      if (HasDialect) hash ^= Dialect.GetHashCode();
      if (Endpoint.Length != 0) hash ^= Endpoint.GetHashCode();
      hash ^= Properties.GetHashCode();
      hash ^= aliases_.GetHashCode();
      if (HasWebsite) hash ^= Website.GetHashCode();
      if (HasMonitor) hash ^= Monitor.GetHashCode();
      if (HasMonitorWebsite) hash ^= MonitorWebsite.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (HasDialect) {
        output.WriteRawTag(34);
        output.WriteString(Dialect);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(output, _map_properties_codec);
      aliases_.WriteTo(output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(66);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(74);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(82);
        output.WriteString(MonitorWebsite);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      names_.WriteTo(ref output, _map_names_codec);
      if (Driver.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Driver);
      }
      if (HasDialect) {
        output.WriteRawTag(34);
        output.WriteString(Dialect);
      }
      if (Endpoint.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Endpoint);
      }
      properties_.WriteTo(ref output, _map_properties_codec);
      aliases_.WriteTo(ref output, _repeated_aliases_codec);
      if (HasWebsite) {
        output.WriteRawTag(66);
        output.WriteString(Website);
      }
      if (HasMonitor) {
        output.WriteRawTag(74);
        output.WriteString(Monitor);
      }
      if (HasMonitorWebsite) {
        output.WriteRawTag(82);
        output.WriteString(MonitorWebsite);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += names_.CalculateSize(_map_names_codec);
      if (Driver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Driver);
      }
      if (HasDialect) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Dialect);
      }
      if (Endpoint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Endpoint);
      }
      size += properties_.CalculateSize(_map_properties_codec);
      size += aliases_.CalculateSize(_repeated_aliases_codec);
      if (HasWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Website);
      }
      if (HasMonitor) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Monitor);
      }
      if (HasMonitorWebsite) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MonitorWebsite);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SdmxWebSource other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      names_.Add(other.names_);
      if (other.Driver.Length != 0) {
        Driver = other.Driver;
      }
      if (other.HasDialect) {
        Dialect = other.Dialect;
      }
      if (other.Endpoint.Length != 0) {
        Endpoint = other.Endpoint;
      }
      properties_.Add(other.properties_);
      aliases_.Add(other.aliases_);
      if (other.HasWebsite) {
        Website = other.Website;
      }
      if (other.HasMonitor) {
        Monitor = other.Monitor;
      }
      if (other.HasMonitorWebsite) {
        MonitorWebsite = other.MonitorWebsite;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Dialect = input.ReadString();
            break;
          }
          case 42: {
            Endpoint = input.ReadString();
            break;
          }
          case 50: {
            properties_.AddEntriesFrom(input, _map_properties_codec);
            break;
          }
          case 58: {
            aliases_.AddEntriesFrom(input, _repeated_aliases_codec);
            break;
          }
          case 66: {
            Website = input.ReadString();
            break;
          }
          case 74: {
            Monitor = input.ReadString();
            break;
          }
          case 82: {
            MonitorWebsite = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            names_.AddEntriesFrom(ref input, _map_names_codec);
            break;
          }
          case 26: {
            Driver = input.ReadString();
            break;
          }
          case 34: {
            Dialect = input.ReadString();
            break;
          }
          case 42: {
            Endpoint = input.ReadString();
            break;
          }
          case 50: {
            properties_.AddEntriesFrom(ref input, _map_properties_codec);
            break;
          }
          case 58: {
            aliases_.AddEntriesFrom(ref input, _repeated_aliases_codec);
            break;
          }
          case 66: {
            Website = input.ReadString();
            break;
          }
          case 74: {
            Monitor = input.ReadString();
            break;
          }
          case 82: {
            MonitorWebsite = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
